api_key: sk_c3080639f3d803a0e690bbef0d8d85a238fab2e1e6b4a9fd

voice:
  id: NacdHGUYR1k3M0FAbAia
  model: eleven_multilingual_v2
  stability: 0.9
  similarity: 1.0
  style: 0.1
  speed: 1.2
  volume: 1.0
  compression:
    threshold: -20  # dB
    ratio: 4
    attack: 5        # ms
    release: 50      # ms

radio:
  volume: 0.4
  duck_volume: 0.1
  interval: 300      # seconds
  playlist: RMF_FM.pls

degradation:
  enabled: false
  sample_rate: 32000 
  filter_low: 200    
  filter_high: 4000  
  noise_level: 0.0001  
  bit_depth: 16      
  crackle: 0.0002       
  distortion: 0.0002         