api_key: string
voice:
  id: string
  model: eleven_multilingual_v2
  stability: 1.0
  similarity: 1.0
  style: 1.0
  speed: 0.5
volumes:
  master: 2.0
  radio: 1.0
  ducking: 1.0
  voice: 2.0
  compression:
    threshold: 0.0
    ratio: 2.0
    attack: 1.0
    release: 1.0
radio:
  playlist: ''
  interval: 1.0
distortion_simulation:
  enabled: true
  sample_rate: 8000
  distortion: 1.0
  filter_low: 20
  filter_high: 100
  noise_level: 0.5
  bit_depth: 4
  crackle: 0.5
degradation:
  sample_rate: 8000
  distortion: 1.0
  filter_low: 20
  filter_high: 100
  noise_level: 0.5
  bit_depth: 4
  crackle: 0.5
