api_key: sk_91ff39808f369a43d4f7e9844c94fd6bcd30f19b8bee2c05
voice:
  id: NacdHGUYR1k3M0FAbAia
  model: eleven_multilingual_v2
  stability: 0.7
  similarity: 0.95
  style: 0.3
  speed: 1.0
volumes:
  master: 1.59
  radio: 0.63
  ducking: 0.11
  voice: 1.96
  compression:
    threshold: -20.0
    ratio: 4.0
    attack: 5.0
    release: 50.0
radio:
  playlist: RMF_FM.pls
  interval: 5.0
distortion_simulation:
  enabled: false
  sample_rate: 32000
  distortion: 0.0002
  filter_low: 200
  filter_high: 4000
  noise_level: 0.0001
  bit_depth: 16
  crackle: 0.0002
