api_key: sk_c3080639f3d803a0e690bbef0d8d85a238fab2e1e6b4a9fd
voice:
  id: NacdHGUYR1k3M0FAbAia
  model: eleven_multilingual_v2
  stability: 0.7
  similarity: 0.95
  style: 0.3
  speed: 1.0
volumes:
  master: 1.0
  radio: 0.5
  ducking: 0.1
  voice: 1.0
  compression:
    threshold: -20.0
    ratio: 4.0
    attack: 5.0
    release: 50.0
radio:
  playlist: RMF_FM.pls
  interval: 300
distortion_simulation:
  enabled: False
  sample_rate: 32000
  distortion: 0.0002
  filter_low: 200
  filter_high: 4000
  noise_level: 0.0001
  bit_depth: 16
  crackle: 0.0002
degradation:
  sample_rate: 8000
  distortion: 1.0
  filter_low: 20
  filter_high: 100
  noise_level: 0.5
  bit_depth: 4
  crackle: 0.5